#基本配置
#DebugMode   = "debug"
#ReleaseMode = "release"
Env = "qa" # 环境: qa 测试  pro 生产
Mode="debug"
AppKey = "base64:"

#nsq
#NsqAddr = "10.2.1.148:18150"

#端口
Port=8080

[teacherPcAppInfo]
    AppUrl = ""
    ForcedUpdate = 1
    LastVersion = ""
    Md5 = ""
    UpdateInfo = ""
    New = 0
    ForgetPage = ""
    SignupPage = ""

[studentPcAppInfo]
    AppUrl = ""
    ForcedUpdate = 1
    LastVersion = ""
    Md5 = ""
    UpdateInfo = ""
    New = 0
    MinVersion = ""
    ForgetPage = ""
    SignupPage = ""

[studentAndroidInfo]
    AppID = ""
    AppUrl = ""
    ForcedUpdate = 1
    LastVersion = ""
    Md5 = ""
    UpdateInfo = ""
    New = 0
    MinVersion = ""
    Size = ""

[studentAndroidAppInfo]
    AppID = ""
    AppUrl = ""
    ForcedUpdate = 1
    LastVersion = ""
    Md5 = ""
    UpdateInfo = ""
    New = 0
    MinVersion = ""
    Size = ""

[studentIosInfo]
    AppID = ""
    AppUrl = ""
    ForcedUpdate = 1
    LastVersion = ""
    Md5 = ""
    UpdateInfo = ""
    New = 0
    MinVersion = ""
    Size = ""

[studentIosAppInfo]
    AppID = ""
    AppUrl = ""
    ForcedUpdate = 1
    LastVersion = ""
    Md5 = ""
    UpdateInfo = ""
    New = 0
    MinVersion = ""
    Size = ""

[log]
#debug info warn error 
logLevel="debug"
logFile="./config_server.log"
isDebug=1

#mysql 配置
#[mysql]
#	Host=""
#	Password = ""
#	User = "wenba"
#	Database = "fudao_course_dev"
#	Maxlifetime = 5
#	MaxidleConns = 10

#redis 配置
#[redis]
#	Server = ""
#	Password = ""
#	RedisMaxIidleConn = 5
#	RedisIdleTimeoutSec = 240
#	SelectDb = 5

#[classRoomRedis]
#    Server = ""
#    Password = ""
#    RedisMaxIidleConn = 5
#    RedisIdleTimeoutSec = 240
#    SelectDb = 0
